#include <iostream>
#include "Functions.h"

using std::cout;
using std::cin;
using std::endl;

void changelog() // display's the changes made over the course of the program's development
{
	cout << "================================================================================================================" << endl;
	cout << "Changelog:" << endl;
	cout << "================================================================================================================" << endl;
	cout << endl;
	cout << "---------------------------" << endl;
	cout << "Changes in current version:" << endl;
	cout << "---------------------------" << endl;
	cout << " Version 2.5.3" << endl;
	cout << "	- Retargeted the project to Visual Studio 2017 (Platform Toolset v141)" << endl;
	cout << "	- Minor code refactoring to increase efficiency throughout the program" << endl;
	cout << endl;
	cout << "-----------------------------" << endl;
	cout << "Changes in previous versions:" << endl;
	cout << "-----------------------------" << endl;
	cout << " Version 2.5.2" << endl;
	cout << "	- Removed one of the secret Easter Eggs because it was stupid" << endl;
	cout << endl;
	cout << " Version 2.5.1" << endl;
	cout << "	- Added secret Easter Eggs" << endl;
	cout << endl;
	cout << " Version 2.5.0:" << endl;
	cout << "	- Added difficulty selection for all subject areas" << endl;
	cout << endl;
	cout << " Version 2.4.4:" << endl;
	cout << "	- Changed method for yes/no answer validation to use tolower()" << endl;
	cout << endl;
	cout << " Version 2.4.3:" << endl;
	cout << "	- Moved random number generation from ProgramBody.cpp to Main.cpp" << endl;
	cout << "	- Minor code refactoring to increase efficiency throughout the program" << endl;
	cout << endl;
	cout << " Version 2.4.2:" << endl;
	cout << "	- Changed addition, subtraction, and multiplication question format to match division" << endl;
	cout << "	- Minor code refactoring to increase efficiency throughout the program" << endl;
	cout << endl;
	cout << " Version 2.4.1:" << endl;
	cout << "	- Minor changes to formatting of stats output" << endl;
	cout << endl;
	cout << " Version 2.4.0:" << endl;
	cout << "	- Added new subject areas:" << endl;
	cout << "		- Combined addition and subtraction" << endl;
	cout << "		- Combined multiplication and division" << endl;
	cout << "		- All subjects in succession" << endl;
	cout << "	- Minor changes to formatting and wording of welcome message" << endl;
	cout << endl;
	cout << " Version 2.3.4:" << endl;
	cout << "	- Minor changes to formatting and wording throughout the program" << endl;
	cout << endl;
	cout << " Version 2.3.3:" << endl;
	cout << "	- Minor changes to formatting and wording throughout the program" << endl;
	cout << endl;
	cout << " Version 2.3.2:" << endl;
	cout << "	- Answers to subtraction subject area problems are now always positive" << endl;
	cout << "	- Changed the format of the changelog" << endl;
	cout << endl;
	cout << " Version 2.3.1:" << endl;
	cout << "	- Subject areas now output the correct answer if the user chooses not to retry a question" << endl;
	cout << endl;
	cout << " Version 2.3.0:" << endl;
	cout << "	- Added file output to output the user's stats to a text file" << endl;
	cout << endl;
	cout << " Version 2.2.0" << endl;
	cout << "	- Added a function to display the changelog" << endl;
	cout << endl;
	cout << " Version 2.1.1:" << endl;
	cout << "	- Modified stats so that question retries are tracked separately from regular question attempts" << endl;
	cout << "	- Minor code refactoring to increase efficiency throughout the program" << endl;
	cout << endl;
	cout << " Version 2.1.0:" << endl;
	cout << "	- Removed welcome function and moved its functionality back to main()" << endl;
	cout << "	- Added 'User' class and global stats tracking via a pointer to a 'User' object" << endl;
	cout << endl;
	cout << " Version 2.0.0:" << endl;
	cout << "	- Separated functions into multiple files with a header file and each function in its own .cpp file" << endl;
	cout << "	- Changed program name from 'Semestor Project' to 'Math Tutor'" << endl;
	cout << endl;
	cout << " Version 1.0.0:" << endl;
	cout << "	- Minor code refactoring throughout the program in preparation for final project submission for credit" << endl;
	cout << endl;
	cout << " Version 0.5.0:" << endl;
	cout << "	- Moved welcome message into its own function" << endl;
	cout << "	- Moved program menu into its own function" << endl;
	cout << "	- Moved switch statement into its own function" << endl;
	cout << "	- Minor code refactoring to increase efficiency throughout the program" << endl;
	cout << endl;
	cout << " Version 0.4.0:" << endl;
	cout << "	- Added the option to retry a problem in the case of an incorrect answer" << endl;
	cout << "	- Moved each subject area into its own function" << endl;
	cout << "	- Each subject area now gives ten random problems" << endl;
	cout << endl;
	cout << " Version 0.3.0:" << endl;
	cout << "	- Added ability to validate answers to problems" << endl;
	cout << "	- Added program menu and switch statement" << endl;
	cout << "	- Added initial versions of addition, subtraction, multiplication, and division subject areas" << endl;
	cout << endl;
	cout << " Version 0.2.0:" << endl;
	cout << "	- Added welcome message" << endl;
	cout << "	- Program now presents the user with one simple, multiple choice addition problem" << endl;
	cout << endl;
	cout << " Version 0.1.0:" << endl;
	cout << "	- Program outputs its name, description, and subject areas" << endl;
	cout << endl;
	cout << " Version 0.0.0:" << endl;
	cout << "	- Created Math Tutor project as 'Semester Project'" << endl;
	cout << endl;
	cout << "================================================================================================================" << endl << endl;
}